cask_args appdir: '/Applications'

tap 'caskroom/fonts'
tap 'homebrew/bundle'
tap 'neovim/neovim'

brew 'ack'
brew 'cmake'
brew 'coreutils'
brew 'curl'
brew 'git'
brew 'grc'
brew 'nmap'
brew 'neovim'
brew 'node'
brew 'openssl'
brew 'python3'
brew 'reattach-to-user-namespace'
brew 'tree'
brew 'tmux'
brew 'vim'
brew 'wget'
brew 'zplug'
brew 'zsh'

cask 'datagrip'
cask 'firefox-developer-edition'
cask 'google-chrome'
cask 'intellij-idea'
cask 'iterm2'
cask 'postman'
cask 'pycharm'
cask 'slack'
cask 'spectacle'
cask 'visual-studio-code'

